### ISSUE TITLE
Adding slash command support

### ISSUE THREAD

**Issue by bleudev** [bleudev/pytecord_old_archive#3]
Adding slash command support for creating bots on dispy. Its must have this code:
```python
@bot.slash(name="Test")
async def test(ctx: SlashContext):
    await ctx.send("Hi!")
```
Checklist:
- [x] Registering slash command
- [x] Answer to slash command
- [x] Adding options
- [x] Adding receving options

**Comment by bleudev** [comment]
This feature for `v 2.0`

**Comment by itttgg** [comment]
Checklist:
- [ ] Registering slash command
- [ ] Answer to slash command
- [ ] Adding options
- [ ] Adding receving options
